### PR TITLE
Added constructor with passed-in word list array

### PR DESCRIPTION
**Pull request by jackcsk**
1. updated: added constructor with passed-in word list array
2. updated: added testcase for the library
3. updated: added usage to README
4. updated: travis-ci config file now includes php-unit test for the different constructors
5. updated: composer.lock for php-5.3 compatibility

### CODE REVIEW

**Comment by jackcsk** [comment]
Sorry for the hurdles, as I found that the last pull request was from a branch I used to test the travis-ci change

**Comment by mofodojodino** [comment]
I've found a better way where this is all handled in travis instead of messing with the composer.lock file which will cause issues long term.

**Comment by mofodojodino** [comment]
Ok, sorry for the mess around I've fixed the test builds on travis so the project is not dependant on composer.lock anymore. If you could update this PR with the composer from develop then I can merge this in. You aren't required to do any fancy `composer update` hacks to get this to work anymore.

**Comment by jackcsk** [comment]
Thx. I've merged the updates, but it seems like travis-ci doesn't install phpunit properly?

**Comment by mofodojodino** [comment]
I think I know what the problem is. If you do a composer update and commit the lock file it should work. Without the lock file updated to include phpunit the 2 that failed will always fail. Those failed tests are testing the installed composer.lock file. The other tests run composer update in one form or another which means the package gets installed on those. Anyway update and it should all start working.

**Comment by jackcsk** [comment]
I've deleted the composer.lock, and it will be re-generated on next "composer install". That fixes the travis-ci issue.

**Comment by mofodojodino** [comment]
Please add the lock file back based on the lock file in the develop branch will be fine and this will work for your PR to. I can't accept this PR without the lock file or the lock file you previously generated with the php 5.3 dependancy that you then removed.

**Comment by jackcsk** [comment]
@mofodojodino: I've added the composer.lock file as you requested. I have to run ```composer update``` to update the composer.lock for the phpunit to install.

**Comment by mofodojodino** [comment]
Thanks @jackcsk

**Comment by developerdino** [comment]
Hey @jackcsk, just letting you know I've released your contribution as v1.3.0. Thanks for you contribution. 

https://github.com/mofodojodino/ProfanityFilter/releases/tag/1.3.0

**Pull request merged**
