### PR TITLE
added constructor with word list array & updated doc

### PR DESCRIPTION
**Pull request by jackcsk**
1. updated: added constructor with passed-in word list array
2. updated: added testcase for the library
3. updated: added usage to README

Signed-off-by: Jack Cheung <jack@jackcheung.com>

### CODE REVIEW

**Comment by jackcsk** [comment]
updated: added constructor with passed-in word list array
    updated: added testcase for the library
    updated: added usage to README

**Comment by mofodojodino** [comment]
Hi Jack,

I had to update the develop branch composer dependancies to make the Travis CI tests pass because the project was pulling in symfony 3 components which aren't php 5.3/5.4 compatible anymore.

This has caused merge conflicts on your PR - sorry. Could you please fix this and I'll merge them in for you.

Also thanks for the contribution, this is much appreciated and I'm glad someone is finding this package useful.

**Comment by mofodojodino** [comment]
Also I just noticed that you didn't add phpunit to the .travis.yml file which means your tests will not run in CI.

**Comment by jackcsk** [comment]
yes, I've figured out that it's the composer.lock update that breaks the travis-ci test. I'll fix that on my end and submit a pull request again.

**Comment by mofodojodino** [comment]
Hi Jack I've already fixed that upstream, you just need to fix the conflict
it has created and add the phpunit command to travis and you should be good
to go.

**Comment by jackcsk** [comment]
Thx. I've fixed the php-5.3 compatibility issue and submitted a pull request.
What I did was put in the config->platform node in composer.json, run composer update to update the composer.lock and then remove the line.
Tested with travis-ci and it looked fine.

**Pull request closed without merging**
